### ISSUE TITLE
Rename python module names to lower-case

### ISSUE THREAD

**Issue by ravidbro** [beyond-io/StuDash#18]
There are industry conventions when coding with python.
You should be aligned to these conventions, and as part of it, all your modules (directory names that contain python files) need to be written without uppercase letters.
https://www.python.org/dev/peps/pep-0008/#package-and-module-names

**Comment by ifireball** [comment]
Please keep it as is - changing it now can be very painful. Since it was auto-generated, it might be mentioned in many places in the code.

**Comment by noaramon** [comment]
Anyway the PR is ready if you would like to reopen the issue.

**Comment by ravidbro** [comment]
You are welcome to open the PR if you already have it ready and working
