### ISSUE TITLE
Grades list & GPA calculator - Tests for the data model functions

### ISSUE THREAD

**Issue by meitals91** [beyond-io/StuDash#29]
Checking the data model functions.

**Comment by lmilbaum** [comment]
This is a duplicate issue. Tests for a specific feature is by default one of the items in the Acceptance Criteria. Close this issue and add it to the other issue acceptance criteria.

**Comment by meitals91** [comment]
@lioramilbaum  You  mean to add it to 'Grades list & GPA calculator - Migration files for creating test data for your DEV environment #26' ?

**Comment by lmilbaum** [comment]
> @lioramilbaum You mean to add it to 'Grades list & GPA calculator - Migration files for creating test data for your DEV environment #26' ?

correct
