### ISSUE TITLE
Favorite link list- Tests for the data model functions

### ISSUE THREAD

**Issue by noaramon** [beyond-io/StuDash#30]
Reassuring that the functions are working.

**Comment by lmilbaum** [comment]
Can you please provide a more details description to what this issue is all about?

**Comment by noaramon** [comment]
This issue is about making sure our data model methods are working as expected by writing tests to each method.
The PR that is linked to this issue should contain a test data and a test file (and might contain modifications in the data model) .

**Comment by lmilbaum** [comment]
> This issue is about making sure our data model methods are working as expected by writing tests to each method.
> The PR that is linked to this issue should contain a test data and a test file (and might contain modifications in the data model) .

Now, I understand better what this issue all about. For the future, you might provide a detailed issue description. The information is used by the reviewer to figure out what this effort all about as a context for the code contribution.
