### ISSUE TITLE
both course and grade have User relation

### ISSUE THREAD

**Issue by simzacks** [beyond-io/StuDash#72]
In PR #67, user was added as a reference to the Course model. The comment by @or313  was that this is by design because each user should add his own courses and there are no "system" courses. 
In this case, the Grade table should not have user referenced, as it is referencing course (which has user).
The problem that can be caused by this is a course that belongs to one user and a grade that belongs to another.

**Comment by simzacks** [comment]
@Omeramsc - FYI, you approved the PR

**Comment by or313** [comment]
@simzacks I guess you are right.. i will have a look into it shortly, thanks

**Comment by simzacks** [comment]
Aside from this, when adding the field user to the course model, you also have to go modify the forms, views and tests that add/update this model so that it includes the user relation.

**Comment by noaramon** [comment]
As a group, we decided to keep only one ref. to user and it will be in the Course class.
I made the necessary changes in my data model as part of my last PR and Meital will do the same in her Grade class.

**Comment by meitals91** [comment]
I made my changes  in my data model.
